# Profile
spring.profiles.active=dev

# Application
spring.application.name=user-management

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.introspection.enabled=true
spring.graphql.websocket.path=/graphql-ws

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/usermanagement?currentSchema=app
spring.datasource.username=um_admin
spring.datasource.password=SecureP@ssw0rd2024!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.schema=app
spring.datasource.hikari.connection-init-sql=SET search_path TO app,public

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Logging
logging.level.bizz.addonai.users.msuserspoc.services=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.graphql=TRACE
logging.level.bizz.addonai.users.msuserspoc.controllers=TRACE